### ISSUE TITLE
Combining Foreground_balanced_pos_sampler and pRoI_generator 

### ISSUE THREAD

**Issue by ch-ho00** [kemaloksuz/BoundingBoxGenerator#2]
Hi. First of all thank you for open sourcing the great work!
I have been trying to make use of  pRoI_generator to generate more RoI on minor classes in my object detection dataset.
But by running the code, it seems like all the RoI's are being generated regardless of the class type (major/minor). And it seems like Foreground balanced pos sampler is a sampler attempt to resolve this issue through selecting minor classes with higher random probability. 

So my question is whether there is a way to generate additional RoI samples specifically belonging to a minor class not all positive samples? Would overwriting random_sampler's _sample_pos function with ForegroundBalancedPosSampler's _sample_pos suffice?

Lastly I think this following line,

`            inputBoxSetExtended[indexPointer:indexPointer+perInputAllocation[i],:4] = self.unnormalize(inputBoxSetExtended[indexPointer:indexPointer+perInputAllocation[i],:4], scales[i], shifts[i])
`

should be added (line 150 of mmdet/core/bbox/samplers/bounding_box_generator.py) before it goes through the process of calculation of IOU) in order to unnormalize the ground truth boxes. 

`
        generated_box_overlaps=self.computeBoxToBoxIoU(inputBoxSetExtended[:,:4],sampledBoxSet).squeeze()
`

For me, if not adding this line, my `generated_box_overlaps` is equal to zero for all generated boxes. 
Please do let me know if I am misunderstanding these concepts/code.
Any response will be appreciated! Thank you.

**Comment by kemaloksuz** [comment]
Hi. Thank you for your interest in our work. Below are the replies.

"So my question is whether there is a way to generate additional RoI samples specifically belonging to a minor class not all positive samples? Would overwriting random_sampler's _sample_pos function with ForegroundBalancedPosSampler's _sample_pos suffice?"

Yes, you can combine the RoIs obtained from the RPN for majority classes and RoIs generated by pRoI Generator for minority classes.  If I wanted to do that, I think I would write a class similar to [pRoI Generator](https://github.com/kemaloksuz/BoundingBoxGenerator/blob/master/mmdet/core/bbox/samplers/pRoI_generator.py). I think, a naive solution can be to call _sample_pos function as in [random sampler](https://github.com/kemaloksuz/BoundingBoxGenerator/blob/master/mmdet/core/bbox/samplers/random_sampler.py) for majority classes (Note that it is currently omitted in pRoI Generator); and then use pRoI Generator for minority classes. You can also call [foreground balanced pos sampler](https://github.com/kemaloksuz/BoundingBoxGenerator/blob/master/mmdet/core/bbox/samplers/foreground_balanced_pos_sampler.py) for majority classes; and then use pRoI Generator for minority classes. These are all possible, and it should not be difficult to manipulate the current code.

"Lastly I think this following line should be added (line 150 of mmdet/core/bbox/samplers/bounding_box_generator.py) before it goes through the process of calculation of IOU) in order to unnormalize the ground truth boxes."

It seems you are right. I will confirm it by myself when I have enough time again, then correct it. Thanks.

If you have more questions, please do not hesitate.

**Comment by ch-ho00** [comment]
Thank you for the answer! My questions are resolved. Appreciate your work again :)

**Comment by kemaloksuz** [comment]
Hi, 

You were right about unnormlization. I have now fixed it.  I found it better to add the line you recommended in line 135 instead of 150. Now, you can get the boxes with IoU as you desire.

Thanks again
